[suit.templates.package.scripts]

lint-pylint = """
pylint --rcfile="{root.path}/.pylintrc" "{local.path}/{args.package_dir}"
"""

lint-black = """
black --check --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"
"""

lint = [
    "lint-pylint",
    "lint-black",
]


format-black = """
black --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"
"""
