[suit.templates.package.scripts]
format-black = 'black --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'
lint = [
  'black --check --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"',
  'pylint --rcfile="{root.path}/.pylintrc" "{local.path}/{args.package_dir}"',
]
lint-black = 'black --check --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'
lint-pylint = 'pylint --rcfile="{root.path}/.pylintrc" "{local.path}/{args.package_dir}"'
