[suit.templates.package.scripts]
## Quality
format = [
  {ref = 'format:black'},
]
'format:black' = 'black --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'

lint = [
  {ref = "lint:black"},
  {ref = "lint:pylint"},
]
'lint:black' = 'black --check --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'
'lint:pylint' = 'pylint --rcfile="{root.path}/.pylintrc" "{local.path}/{args.package_dir}"'

'tests:install-dependencies' = 'pip install pytest'
'tests:run' = 'pytest {local.path}/{args.tests_dir}'

tests = [
  {ref = 'tests:install-dependencies'},
  {ref = 'tests:run'}
]

## Deployment
build = [
  'pip install build',
  'python -m build "{local.path}"',
]

publish = [
  'pip install twine',
  'twine upload --non-interactive --disable-progress-bar {local.path}/dist/*',
]

deploy = [
  {ref = 'build'},
  {ref = 'publish'},
]
