[suit.templates.package.scripts]
'format' = [
  {ref = 'format:black'},
]
'format:black' = 'black --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'

'lint' = [
  {ref = "lint:black"},
  {ref = "lint:pylint"},
]
'lint:black' = 'black --check --config "{root.path}/pyproject.toml" "{local.path}/{args.package_dir}"'
'lint:pylint' = 'pylint --rcfile="{root.path}/.pylintrc" "{local.path}/{args.package_dir}"'
